[package]
name = "llcat-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.90", features = ["full"] }
quote = "1.0.37"
attribute-derive = "0.10.3"

[lib]
proc-macro = true
